# Config file for plexmediafixup project
#
# Note: This is an example file that should be copied and updated as needed.

servername: "SERVERNAME"    # Server name of the Plex Media Server (not IP or hostname)
username: "USERNAME"        # Username (email) of the Plex Account
password: "PASSWORD"        # Password of the Plex Account

fixups:

  - name: sync_sort_title
    title: Set sort title field to value of title field
    enabled: true
    kwargs:
