# plexmediafixup config file

# Path name of PlexAPI config file. Omitting this value or specifying null
# causes the PlexAPI default to be used (i.e. env var PLEXAPI_CONFIG_PATH or
# ~/.config/plexapi/config.ini).
plexapi_config_path: null

# Flag controlling whether connection is directly to the Plex Media Server
# (true) or indirectly via the Plex web site (false). Using direct
# connection requires the PlexAPI config file parameters auth.server_baseurl
# and auth.server_token to be set. Using indirect connection requires the
# PlexAPI config file parameters auth.myplex_username and auth.myplex_password
# to be set, as well as the server_name parameter in this config file.
direct_connection: true

# Server name of the Plex Media Server. This is not the IP address or host
# name, but the server name that can be found in the top left corner of the
# Plex web GUI. This parameter is only required for indirect connection.
server_name: "SERVERNAME"

# File path mappings between the file system seen by the Plex Media Server
# (item 'server'), and the file system seen by the plexmediafixup command
# (item 'local'). A value of null means there is no file path mapping
# needed. The file path mappings in this list are processed in the
# specified order when mapping a file path.
path_mappings:
  - server: /
    local: /

# Definitions for video genre cleanup
video_genre_cleanup:

  # one list item for each language.
  -

    # Language to which this list item applies, using the two-letter language
    # codes defined in ISO 639-1.
    language: de

    # Genres to be changed.
    # The changes are defined in a dictionary, where the dictionary key is
    # the desired genre, and the dictionary value is a (possibly empty)
    # list of original genres that will be changed to the desired genre.
    # If an original genre does not match any of those, it is left
    # unchanged. If an original genre occurs in multiple desired genres,
    # it is changed to all those desired genres.
    change:
      Abenteuer:
        - Action & Adventure
        - Adventure
      Action:
        - Action & Adventure
      Anime:
      Biographie:
        - Biography
      Dokumentation:
        - Documentary
        - Dokumentarfilm
      Eastern:
      Erotik:
      Familie:
        - Family
        - Kinder-/Familienfilm
      Fantasy:
      Film-Noir:
        Film Noir
      Historie:
        - Historienfilm
        - History
      Horror:
        - Grusel
      Kampfsport:
      Katastrophen:
      Kinder:
        - Children
        - Kids
        - Kinder-/Familienfilm
      Komödie:
        - Comedy
      Krieg:
        - Kriegsfilm
        - War
      Krimi:
        - Crime
        - Krimireihe
      Liebe/Romantik:
        - Liebesfilm
        - Romance
      Live-Show:
      Melodram:
        - Drama
      Musik:
        - Music
        - Musikfilm
      Musical:
      Mystery:
      Reality:
      Reisen:
        - Travel
      Satire:
      Science-Fiction:
        - Sci-Fi
        - Science Fiction
      Soap:
      Spannung:
        - Suspense
      Special Interest:
      Splatter:
      Sport:
        - Sportfilm
      Stummfilm:
      Talk-Show:
        - Talk Show
      Thriller:
      Tiere:
        - Tierfilm
      Trickfilm:
        - Animation
      Western:

    # Genres to be removed.
    remove:
      - k.A.
      - K.A.
      - Mini-Series
      - TV Movie
      - TV-Film
      - TV-Mini-Serie
      - TV-Pilotfilm
      - Kurzfilm

    # Genre to be set if the item has an empty list of genres.
    # A value of null causes the list of genres to remain empty in that case.
    if_empty: "<keins>"

# List of fixups. The same fixup can be specified more than once. The enabled
# fixups in this list will be run in the specified order.
#
# Each fixup has the following general parameters:
#
# * name: Name of the fixup. This is the module name (= base file name) in the
#   plexmediafixup/fixups directory. Required.
#
# * enabled: Boolean flag controlling whether the fixup should run. Required.
#
# * kwargs: An object (=dict) with fixup-specific parameters that are passed
#   to the fixup. These parameters are described below for each fixup.
#
fixups:

  # sync_title is a fixup that walks through the movie and episode items of
  # the configured library sections, and syncs the "title" field of each item
  # by setting it to the value of the title tag found in the corresponding
  # media files.
  - name: sync_title
    enabled: true
    kwargs:

      # String or list of strings that specify the library section types that
      # should be processed. Valid values are: 'movie', 'show'. For 'show',
      # only the episode items of the show items will be processed, but not the
      # show items themselves. A value of null means to process all valid
      # section types. Optional, default is null.
      section_types: null

      # String that specifies a regex pattern defining library section names
      # that should be processed within the configured section types. A value
      # of null means to process all library sections of the configured types.
      # Optional, default is null.
      section_pattern: null

  # sync_sort_title is a fixup that walks through the movie, show and episode
  # items of the configured library sections, and syncs the "sort title" field
  # of each item by setting it to the value of its "title" field.
  - name: sync_sort_title
    enabled: true
    kwargs:

      # String or list of strings that specify the library section types that
      # should be processed. Valid values are: 'movie', 'show'. For 'show',
      # both the show items themselves and their episode items will be
      # processed. A value of null means to process all valid section types.
      # Optional, default is null.
      section_types: null

      # String that specifies a regex pattern defining library section names
      # that should be processed within the configured section types. A value
      # of null means to process all library sections of the configured types.
      # Optional, default is null.
      section_pattern: null

      # Boolean that controls whether the sort title will be translated to
      # 7-bit ASCII using the unidecode package.
      as_ascii: true

      # Boolean that controls whether special characters will be removed from
      # the sort title.
      remove_specials: true

  # video_genre_cleanup is a fixup that walks through the movie and show items
  # of the configured library sections, and cleans up the "Genres" field of
  # each item. It can consolidate genres into a defined list of genres, remove
  # useless genres, and set a default genre if the list of genres is empty.
  # These changes can be configured in the "video_genre_cleanup" config
  # parameter.
  - name: video_genre_cleanup
    enabled: true
    kwargs:

      # String or list of strings that specify the library section types that
      # should be processed. Valid values are: 'movie', 'show'. For 'show',
      # only the show items will be processed, but not the episodes (they do
      # not define a separate genre). A value of null means to process all
      # valid section types.
      # Optional, default is null.
      section_types: null

      # String that specifies a regex pattern defining library section names
      # that should be processed within the configured section types. A value
      # of null means to process all library sections of the configured types.
      # Optional, default is null.
      section_pattern: null

      # Language to be used to select the genre cleanup definitions from the
      # "video_genre_cleanup" config parameter, using the two-letter language
      # codes defined in ISO 639-1.
      language: de
